config_name: 'cora_gru'

DISTRIBUTED:
  world_size: 4
  port: 1427

DATASET:
  directory: '/fs/nexus-scratch/khoi/cora_cvpr2024/data/f30k'
  split: 'train'

MODEL:
  img_dropout: 0.1
  img_encoder_type: 'region'
  img_pooling_type: 'gpo-selfattn'  # 'avg' or 'gpo-selfattn'
  img_pos_embed_dim: 16
  
  word_embed_source: 'scratch'
  word_embed_dim: 300

  entity_composer_method: 'gru'
  entity_composer_hidden_dim: 1024
  entity_composer_n_layers: 1
  entity_composer_dropout: 0.15

  rel_composer_method: 'gru'
  rel_composer_hidden_dim: 1024
  rel_composer_n_layers: 2
  rel_composer_dropout: 0.15

  graph_pos_embed_dim: 16
  use_graph_global: False

  embed_dim: 1024
  freeze_bert: False

  weights: ''
  optim_weights: ''
  pretrained_word_embedding_path: ''

TRAIN:
  checkpoint_directory: '/fs/nexus-scratch/khoi/cora_cvpr2024/checkpoints/f30k'

  seed: 1742
  num_workers: 12

  ###########################################
  ######## OPTIMIZER/LOSS HYPERPARAMS #######
  ###########################################

  batch_size: 128
  start_epoch: 0
  start_evaluate_epoch: 1
  num_epochs: 55

  ####### Losses
  contrastive_temperature: 0.01

  ####### Specificity loss
  specificity_loss_weight: 11.0
  specificity_margin: 0.35
  #############################

  ####### Hardest triplet loss
  image_caption_hardest_loss_weight: 4.0
  hardest_margin: 0.35
  #############################

  lr_img: 5e-4                  # learning rate for image encoder
  lr_word: 5e-4                 # learning rate for word embedding
  lr: 5e-4                      # learning rate for other modules
  lr_warmup_epochs: 1           # num epochs to warm up
  weight_decay: 1e-4
  clip_grad: -1.0               # set to -1 if don't want to apply clip grad

  lr_decay_epochs: [15]         # epoch to decay learning rate
  lr_decay_rate: 0.1            # learning rate decay factor

  ###########################################
  ######## DATA SAMPLING HYPERPARAMS ########
  ###########################################

  region_dropout: True          # whether to apply region dropout
  region_dropout_prob1: 1.00    # probability to drop region for an image
  region_dropout_prob2: 0.35    # probability to drop a region
  grid_dropout: 0.2             # only use for grid features

  max_n_entities: 13            # max num entities per image
  max_n_entity_tokens: 8        # max num tokens per entity
  max_n_attributes: 4           # max num attributes per entity
  max_n_attribute_tokens: 5     # max num tokens per attribute
  max_n_relations: 13           # max num relations per image
  max_n_relation_tokens: 9      # max num tokens per relation

  prob_drop_entity: 0.05        # prob to drop an entity from scene graph
  prob_drop_attribute: 0.15     # prob to drop an attribute
  prob_drop_relation: 0.15      # prob to drop a relation
  
  prob_mask_entity_token: 0.10        # prob to mask entity tokens 
  prob_delete_entity_token: 0.05      # prob to delete entity tokens
  prob_replace_entity_token: 0.0      # prob to randomly replace entity token with another token
  
  prob_mask_relation_token: 0.10      # prob to mask entity tokens 
  prob_delete_relation_token: 0.05    # prob to delete relation tokens
  prob_replace_relation_token: 0.0    # prob to randomly replace relation token with another token

  prob_singularize_obj: 0.125   # prob to singularize an object name
  prob_pluralize_obj: 0.10      # prob to pluralize an object name

  disp_interval: 300
  eval_every_epoch: 1